### ISSUE TITLE
App crashes as 'libVidyoClient.so' not found

### ISSUE THREAD

**Issue by shravyav1991** [Vidyo/vidyo.io-helloworld-android#15]
I am implementing vidyo to my android app.

However my app crashes with reason 'libVidyoClient.so" not found.

Also, all the folders and jar files  included in "\VidyoClient-AndroidSDK\lib\android"  location are placed in  "C:\Users\name\AndroidStudioProjects\Project\app\lib" folder.

Gradle is changed accordingly. What else is missing here?

**Comment by tmelko-vidyo** [comment]
Are you sure you did all right?
Seems like the path is broken.
Look at the screenshot attached.
<img width="1636" alt="Screen Shot 2019-09-23 at 16 00 35" src="https://user-images.githubusercontent.com/38790517/65427626-6155b180-de1b-11e9-9592-dc9f1661564d.png">

**Comment by shravyav1991** [comment]
Yeah, there was an error in location path. Fixed it
